<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// Lucent Innovation Sarvesh Patel
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */

$query = '';
if(isset($_GET['q']) && $_GET['q']!=''){
     $query = $_GET['q'];
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Request\Http');
?>
<style>
	.filter-options .filter-options-title{
		border: 1px solid #000;
    	padding: 10px;
    	margin: 0 0 0px;
	}
	.filter-options .filter-options-content{
		border-left: 1px solid #000;
		border-right: 1px solid #000;
	    padding-left: 10px;
	    border-bottom: 0;
	    margin-bottom: -3px;
	    padding: 10px;
	}
	dl dd:last-child {
		border-bottom: 1px solid #000 !important;
	}
	.page-title-wrapper{
		    text-align: center;
	}
	.cprice{
		font-size: 22px;
   		line-height: 40px;
   		color: #888;
	}
	.purl,a.purl:visited{
		height: 31px;
	    float: left;
	    margin: 10px 0px;
	    color: #888;
	}
	.filter-options-content li div span{
		z-index: -1;
		position: relative;
	}
	.filter-options-content li div{
		z-index: 100;
		position: relative;
	}
	.seleoption{
		float: left;
	    width: auto;
	    display: block;
	    min-width: 20px;
	    background: #ccc;
	    margin: 3px;
	    text-align: center;
	    border-radius: 3px;
	    font-size: 16px;
	    padding: 5px 10px;
	}
	.pager{
		color: #999;
	    padding: 10px;
	    font-size: 20px;
	    margin: 10px;
	    border-radius: 16px;
	    background: #ddd;
	    text-decoration: none;
	}
	.pager:hover{
	    text-decoration: none;
	}
	.pagenumber_static{
		color:#000;
	}
	.clicked{
		color:#ff0;
	}
	.swatch-option-selected {
	    border: 1px solid #f00;
	    cursor: pointer;
	    float: left;
	    height: 20px;
	    margin: 0 10px 5px 0;
	    max-width: 100%;
	    min-width: 30px;
	    overflow: hidden;
	    padding: 1px 2px;
	    position: relative;
	    text-align: center;
	    text-overflow: ellipsis;
	}
	.selectedprice{
		color:#f00;
	}

</style>




<?php if ($block->canShowBlock()): ?>
    <div class="block filter">

         <!-- <div class="block-title filter-title">
            <strong><?= /* @escapeNotVerified */ __('Shop By Sarvesh') ?></strong>
        </div> -->
         <div class="block-content filter-content">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="action clear filter-clear"><span><?= /* @escapeNotVerified */ __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>

                <?php if (!$wrapOptions): ?>

<!--                     <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= /* @escapeNotVerified */ __('Shopping Options') ?></strong>
 -->
                    <dl class="filter-options"  id="accordion" data-mage-init='{
        "accordion":{
            "active": [0],
            "collapsible": true,
            "openedState": "active",
            "multipleCollapsible": true
        }}'>
                <?php $wrapOptions = true; endif; ?>
                    <?php if ($filter->getItemsCount()): ?>
                        <dt data-role="collapsible" role="heading" aria-level="3" class="filter-options-title"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd  data-role="content" class="filter-options-content"><?= /* @escapeNotVerified */ $block->getChildBlock('renderer')->render($filter) ?></dd>

                   
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[
 require([
    'jquery',
    'Magento_Ui/js/modal/alert'
    ], function($, alert) {
    	//$('#layer-product-list').html('');
		<?php
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
		if(isset($category)){
		    $category_id = $category->getId();
		}else{
		    $category_id = '';
		}

	    ?>
	    $('.swatch-attribute .swatch-option-link-layered').attr("href","javascript:;");


	   // $('#layer-product-list').html('<center style="font-size:50px;">Loding.....</center>');    	
	   filterProductbyattribute(option_id='',category_id='<?php echo $category_id; ?>',attribute_code='',label='',action='',limit='9',page='1',query='<?php echo $query; ?>',filterpage='<?php echo $request->getRouteName();?>');


       $('.filter-options-content li div').on('click', function(event){
            var option_id= $(event.target).attr('data'),
                attribute_code= $(event.target).attr('code'),
                label= $(event.target).attr('value'),
                category_id= $(event.target).attr('category-id');
                //var ids = option_id+' '+category_id; 
                //alert({ content:attribute_code});
                if(attribute_code=='price'){
                	$('.filter-options-content li div.price_class').removeClass('selectedprice');
                	$(event.target).addClass( "selectedprice" );
                }else if(attribute_code=='category'){
                	category_id= $(event.target).attr('data');
                	$('.filter-options-content li div.category_class').removeClass('selectedprice');
                	$(event.target).addClass( "selectedprice" );
                }else{
                	$(event.target).addClass( "selectedprice" );
                }
 	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),
       // if  override rendered template
       /*
       $('.filter-options-content .swatch-attribute .swatch-attribute-options .swatch-option').on('click', function(event){
                var option_id= $(event.target).attr('option-id'),
                attribute_code= $(event.target).attr('code'),
                label= $(event.target).attr('option-label'),
                category_id= $(event.target).attr('category-id');
                //var ids = option_id+' '+category_id; 
                //alert({ content:ids});
				var action= 'add';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page);
       }),
		*/
       // remove selection filter	
       $('html').on('click','.seleoption', function(event){
       			
	                var option_id= $(event.target).attr('option-id'),
	                attribute_code= $(event.target).attr('data'),
	                label= $(event.target).attr('option-id'),
	                category_id= $(event.target).attr('category-id');
	                var ids = '.'+attribute_code+'_'+label; 
       				//alert({ content:ids});
				if(attribute_code=='price'){
                	$('.price_'+label).removeClass('selectedprice');
				}else if(attribute_code=='brand'){
                	//$('.'+attribute_code+'_'+label).removeClass('swatch-option-selected');
                	$( "div[option-id='"+label+"']" ).removeClass( "swatch-option-selected" );
                }else{
                	$('.'+attribute_code+'_'+label).removeClass('selectedprice');
                }

				var action= 'delete';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),
       // not override rendered template
       $('html').on('click','.swatch-option', function(event){

                var option_id= $(event.target).attr('option-id'),
                attribute_code= $( ".swatch-option" ).parent().parent().parent().attr('attribute-code'),
                category_id= '<?php echo $category_id; ?>',
                label= $(event.target).attr('option-label');
                //var ids = option_id+' '+category_id; 
                //var search_val = $( ".swatch-option" ).parent().parent().parent().attr('attribute-code');
                //alert({ content:search_val});
               
       			$(event.target).addClass( "swatch-option" ).addClass( "swatch-option-selected "+attribute_code+'_'+option_id );
				var action= 'add';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),

       $('html').on('click','.pagenumber', function(event){
       			
                var page= $(event.target).attr('data'),
                limit= $(event.target).attr('limit');
                //var ids = option_id+' '+category_id; 
                //var search_val = $( ".swatch-option" ).parent().parent().parent().attr('attribute-code');
                //alert({ content:page+' '+limit});
               
				var action= 'pagination';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       }),

       // on search click event fire
       $('html').on('click','.searchbtn', function(event){
       			
                var option_id= $(event.target).attr('option-id'),
                attribute_code= $(event.target).attr('data'),
                category_id= $(event.target).attr('category-id'),
                                search_val= $('#search').val(),
                page= $('.pagenumber').attr('data');
                var ids = option_id+' '+category_id; 
                
                alert({ content:search_val});
               
				var action= 'add';	
	       		filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage);
       })


	   function filterProductbyattribute(option_id,category_id,attribute_code,label,action,limit,page,query,filterpage){
		    $('#layer-product-list').html('<center style="font-size:50px;">Loding.....</center>');    	

		   	//alert({content:filterpage});

	        var htmlData = '';
            $.post('<?php  echo $block->getUrl('hello/index/display'); ?>',{ id: option_id,cid: category_id,attribute_code: attribute_code,label: label,action: action,limit: limit,page: page,query: query,filterpage: filterpage},function(data){

							<?php
							if(!isset($_GET['q'])){
								$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); 		
								$category_name = $category->getName();
							?>	            		
			                    htmlData += '<center><h3><?php echo $category_name; ?>'; 
			                    htmlData += '</h3></center>'; 
			                <?php } ?>
            			    //alert({content:data.catalogsearch.values.category});
		                    htmlData += '<div class="row">'; 
		                    if(data.values.category!=''){
		                    	$('.filter-options-content li div').attr('category-id',data.values.category);
			                    htmlData += '<a class="seleoption" data="category" option-id="'+data.values.category+'" value="'+data.values.category+'" category-id="<?php echo $category_id; ?>">'+data.values.categoryLabel+'</a>';  
			    			    $('.category_'+data.values.category).addClass('selectedprice');
		                    }	

			                var  pricefilter = '';
			                if(data.values.price!=''){
			                    var pricedata  = data.values.price;
			                    var priceresult = pricedata.split('-');
			                    //alert({ content:priceresult[1]});
			                    if(priceresult[0] == ''){
			                    	pricefilter += 'less then '+priceresult[1];
			                    }else if (priceresult[1]== ''){
			                    	pricefilter += 'greater then '+priceresult[0];
			                    }else{
			                    	pricefilter += 'from '+priceresult[0]+' to '+priceresult[1];
			                    }
			                    htmlData += '<a class="seleoption" data="price" option-id="'+data.values.price+'" value="'+data.values.price+'" category-id="<?php echo $category_id; ?>">'+pricefilter+'</a>';  
			                 }
		            		var size_data  = data.values.size;
		            		var size_data_label  = data.values.sizelabels;
			                if(size_data.length > 0 ){
			                    for(var a=0;a<size_data.length;a++){
									  $('.size_'+size_data[a]).addClass('selectedprice');
			                          htmlData += '<a class="seleoption" category-id="<?php echo $category_id; ?>" data="size" option-id="'+size_data[a]+'">'+size_data_label[a]+'</a>';  
			                    }
			                }

		            		var color_data  = data.values.color;
		            		var color_data_label  = data.values.colorlabels;
			                if(color_data.length > 0 ){
			                    for(var b=0;b<color_data.length;b++){
									  $('.color_'+color_data[b]).addClass('selectedprice');
			                          htmlData += '<a class="seleoption" category-id="<?php echo $category_id; ?>" data="color" option-id="'+color_data[b]+'">'+color_data_label[b]+'</a>';  
			                    }
			                }

		            		var brand_data  = data.values.brand;
		            		var brand_data_label  = data.values.brandlabels;
			                if(brand_data.length > 0 ){
			                    for(var c=0;c<brand_data.length;c++){
			                    	$( "div[option-id='"+brand_data[c]+"']" ).addClass( "swatch-option-selected" );
			                          htmlData += '<a class="seleoption" category-id="<?php echo $category_id; ?>" data="brand" option-id="'+brand_data[c]+'">'+brand_data_label[c]+'</a>';  
			                    }
			                }
		                    htmlData += '</div><br/><br/>'; 

            		
		            <?php 
				        $currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
				        $currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
				        $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
				        $currencySymbol = $currency->getCurrencySymbol();
					?>       	
                    htmlData += '<div class="row">'; 
	                if(data.products.length > 0 ){

	                    for(var i=0;i<data.products.length;i++){
	                          htmlData += '<div class="col-4" style="margin-bottom:20px;">';  
	                          htmlData += '<div style="width:100%;"><a href="'+data.products[i].url+'"><img style="height:300px;width:100%; display:block;" src="'+data.products[i].image+'"></a></div>';  
	                          htmlData += '<div class="row"><div class="col-12"><a class="purl" href="'+data.products[i].url+'">'+data.products[i].name+'</a></div></div>';  
	                          htmlData += '<div class="row"><div class="col-6"><div class="cprice"> <?php echo $currencySymbol;?> '+data.products[i].price+'</div></div>';  
	                          htmlData += '<div class="col-6" style="text-align:right;">'+data.products[i].addtocart+'</div>';  
	                          htmlData += '</div></div>';  
	                    }
	                }else{
	                    htmlData += '<div class="col-12">No Product Found!</div>'; 
	                }
	                	//pagination jquery 
	                	//var totalProduct =  data.products.length;
	                	//totalpage =  Math.ceil(totalProduct  / 9) ;

	                htmlData += '<div class="col-12">'+data.pagination+'</div>'; 

                    htmlData += '</div>'; 

			    	$('.price_'+data.values.price).addClass('selectedprice');
                   

                    $('#layer-product-list').html(htmlData);
                },'json');
	   }
   }



 );
//]]>
</script>
